### ISSUE TITLE
Explanation for TrappingRainwater

### ISSUE THREAD

**Issue by TheLettuceMan81** [Penguin5681/LeetCodeSolutions#1]

**Comment by Penguin5681** [comment]
you use a stack to keep track of the indices of the elevation map. As you iterate through the elevation map, if you encounter a bar higher than the one at the top of the stack, you pop elements from the stack and calculate the trapped water for each bar. The trapped water is determined by the distance between the current bar and the one at the top of the stack and the minimum height between them. Finally, you push the current bar onto the stack. This way, you calculate the trapped water for each section of the elevation map and accumulate the total trapped water.
